version: '3'

services:
  paymybuddy-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_paymybuddy
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - paymybuddy-network

  paymybuddy-backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - paymybuddy-db
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:mysql://paymybuddy-db:3306/db_paymybuddy
    ports:
      - "8080:8080"
    networks:
      - paymybuddy-network

networks:
  paymybuddy-network:

volumes:
  mysql-data:

