services:
  paymybuddy-backend:
    build: .
    image: paymybuddy-backend:latest
    container_name: paymybuddy-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:mysql://paymybuddy-db:3306/db_paymybuddy
    depends_on:
      - paymybuddy-db
    networks:
      - paymybuddy-network

  paymybuddy-db:
    image: mysql:8.0
    container_name: paymybuddy-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_paymybuddy
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - paymybuddy-network

networks:
  paymybuddy-network:

volumes:
  mysql-data:
