apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymybuddy-db
  template:
    metadata:
      labels:
        app: paymybuddy-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          value: db_paymybuddy
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-db
        configMap:
          name: mysql-init-scripts
