apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-db
  namespace: paymybuddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymybuddy-db
  template:
    metadata:
      labels:
        app: paymybuddy-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          value: db_paymybuddy
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-init-script
        configMap:
          name: mysql-init-script
